#!/usr/bin/env bash


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# update system package archives
sudo apt-get update -qq > /dev/null

# install useful packages for development
sudo apt-get install -qq git > /dev/null

# configure git with username and email
# git config --global user.name "#{gh_user}"
# git config --global user.email "YOUR@EMAIL.com"
