#!/usr/bin/env bash


# @param: version of go to install
args_go_version=${1}

# @param: (optional) path to set for $GOPATH
args_go_gopath=${2}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# download go
wget https://storage.googleapis.com/golang/go${args_go_version}.linux-amd64.tar.gz -O ./go.tar.gz > /dev/null

# unpack go
tar -xvf ./go.tar.gz > /dev/null

# move the binaries
sudo mv go /usr/local

# clean up install files
rm ./go.tar.gz

# make sure we add go to the PATH
echo 'export PATH=$PATH:/usr/local/go/bin' | tee --append ~/.profile

# if $GOPATH is specified, set it
if [ ! -z "${args_go_gopath}" ]; then
    # make sure the directory exists (only use sudo if the normal user can't create it)
    mkdir -p ${args_go_gopath} || sudo mkdir -p ${args_go_gopath}

    # set $GOPATH
    echo "export GOPATH=${args_go_gopath}" | tee --append ~/.profile
fi
