#!/usr/bin/env bash


# @param: version of php to install (e.g. 5.6)
args_php_version=${1}

# @param: (optional) list of php extensions to install
args_php_extensions=${2}

# @param: (optional) user to run php-fpm as, note: if left blank, user will be left as default
args_php_user=${3}

# @param: (optional) group to run php-fpm as, note: if left blank, group will be left as default
args_php_group=${4}

# @param: (optional) owner to run php-fpm as, note: if left blank, owner will be left as default
args_php_owner=${5}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# set locale
export LC_ALL=en_US.UTF-8

# determine the best installation method based on the desired version of php
case ${args_php_version} in
    "7.0"|"5.6"|"5.5")
        # add ppa for 5.6 since it will be a lot faster than using phpbrew
        sudo -E add-apt-repository -y ppa:ondrej/php > /dev/null

        # update repository information
        sudo apt-get update -qq > /dev/null

        # check whether or not apache is already installed before the ppa installs it (useful for determining whether it should stay or be removed)
        apache_is_installed=$(command -v apache2) > /dev/null

        # install specified version of php
        sudo apt-get install -qq "php${args_php_version}" > /dev/null

        # add new apache packages
        sudo apt-get install -qq "libapache2-mod-php${args_php_version}" > /dev/null

        # only remove apache if it wasn't already installed
        if [ -z "${apache_is_installed}" ]; then
            # remove apache since the ppa automatically installs it (this script should be unopinionated)
            sudo apt-get remove -qq apache2 > /dev/null

            # (auto)remove apache sub-packages
            sudo apt-get autoremove -qq > /dev/null
        fi

        # if a string list of packages is passed in, install those packages
        if [ ! -z "${args_php_extensions}" ]; then
            sudo apt-get install -qq ${args_php_extensions} > /dev/null
        fi

        # check for php-fpm
        if [[ ${args_php_extensions} == *"php${args_php_version}-fpm"* ]]; then
            # if a user is specified, overwrite the default user
            if [ ! -z "${args_php_user}" ]; then
                sudo sed -i "s/user = www-data/user = ${args_php_user}/g" /etc/php/${args_php_version}/fpm/pool.d/www.conf > /dev/null
            fi

            # if a group is specified, overwrite the default group
            if [ ! -z "${args_php_group}" ]; then
                sudo sed -i "s/group = www-data/group = ${args_php_group}/g" /etc/php/${args_php_version}/fpm/pool.d/www.conf > /dev/null
            fi

            # if an owner is specified, overwrite the default owner
            if [ ! -z "${args_php_owner}" ]; then
                sudo sed -i "s/owner = www-data/owner = ${args_php_owner}/g" /etc/php/${args_php_version}/fpm/pool.d/www.conf > /dev/null
            fi

            # create symlink for php-fpm socket file (helps with nginx setup)
            sudo ln -s /run/php/php${args_php_version}-fpm.sock /run/php/php-fpm.sock

            # service needs to be restarted after changing configuration
            sudo service php${args_php_version}-fpm restart
        fi
        ;;
esac
