#!/usr/bin/env bash


# @param: name of the DB
args_postgresql_db_name=${1}

# @param: username of the DB user
args_postgresql_db_user=${2}

# @param: password of the DB user
args_postgresql_db_pass=${3}

# @param: allowed hostname
args_postgresql_db_host=${4}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install PostgreSQL
sudo -E apt-get install -qq postgresql postgresql-contrib libpq-dev > /dev/null

# create database
sudo -u postgres psql -U postgres postgres -c "create database ${args_postgresql_db_name};" > /dev/null

# create user
sudo -u postgres psql -U postgres postgres -c "create user ${args_postgresql_db_user} with password '${args_postgresql_db_pass}';" > /dev/null

# create user, and grant all permissions to new DB
sudo -u postgres psql -U postgres postgres -c "grant all privileges on database ${args_postgresql_db_name} to ${args_postgresql_db_user};" > /dev/null
