#!/usr/bin/env bash


# @param: version of ruby to install (e.g. 2.3)
args_ruby_version=${1}

# @param: version of rails to install (e.g. 4.2.5)
args_rails_version=${2}

# @param: list of rails packages to install
args_package_list=${3}

# @param: (optional) user to run rails as, note: if left blank, user will be left as default
args_user=${4}

# @param: (optional) group to run rails as, note: if left blank, group will be left as default
args_group=${5}

# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install dependencies
sudo apt-get install -qq git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev > /dev/null

# clone rbenv, ruby version manager
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"'               >> ~/.bashrc
source ~/.bashrc


git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
sudo -H -u vagrant bash -i -c 'rbenv install 2.3.0' > /dev/null
sudo -H -u vagrant bash -i -c 'rbenv rehash' > /dev/null
sudo -H -u vagrant bash -i -c 'rbenv global 2.3.0' > /dev/null
sudo -H -u vagrant bash -i -c 'gem install bundler --no-ri --no-rdoc' > /dev/null
sudo -H -u vagrant bash -i -c 'gem install rails' > /dev/null
sudo -H -u vagrant bash -i -c 'rbenv rehash' > /dev/null

# install NodeJS, a Javascript runtime for Rails

sudo add-apt-repository ppa:chris-lea/node.js -y >  /dev/null
sudo apt-get -qq update > /dev/null
sudo apt-get -qq install nodejs > /dev/null


