#!/usr/bin/env bash

# @param: version of ruby to install (e.g. 2.3) 
args_ruby_version=${1}

# @param: (optional) user to run ruby as, note: if left blank, user will be left as default
args_user=${2}

# @param: (optional) group to run ruby as, note: if left blank, group will be left as default
args_group=${3}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install dependencies necessary for ruby installation
sudo apt-get -qq install software-properties-common libssl-dev libreadline-dev zlib1g-dev > /dev/null

# clone rbenv, ruby version manager, source to .bashrc
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"'               >> ~/.bashrc
source ~/.bashrc

# clone ruby-build, which will build ruby and set global version
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
sudo -H -u vagrant bash -i -c "rbenv install -v $1" > /dev/null
sudo -H -u vagrant bash -i -c "rbenv rehash" > /dev/null
sudo -H -u vagrant bash -i -c "rbenv global $1" > /dev/null

# install bundler, which will manage gem dependencies for your ruby versions
sudo -H -u vagrant bash -i -c "gem install bundler --no-ri --no-rdoc" > /dev/null
