#!/usr/bin/env bash


# @param: version of ruby to install (e.g. 2.3)
args_ruby_versionn=${1}

# @param: list of ruby packages to install
args_ruby_package_list=${2}

# @param: (optional) user to run php-fpm as, note: if left blank, user will be left as default
args_ruby_user=${3}

# @param: (optional) group to run php-fpm as, note: if left blank, group will be left as default
args_ruby_group=${4}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# determine the best installation method based on the desired version of php
case ${args_ruby_version} in
    "2.3")
        
        # prepare for installation
        sudo apt-get install build-essential

        wget -O ruby-install-0.6.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.0.tar.gz
        tar -xzvf ruby-install-0.6.0.tar.gz
        cd ruby-install-0.6.0/
        sudo make install
        ruby-install --latest ruby 2.3.0
        wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
        tar -xzvf chruby-0.3.9.tar.gz
        cd chruby-0.3.9/
        sudo make install

esac
