#!/usr/bin/env bash


# @param: version of ruby to install (e.g. 2.3)
args_ruby_version=${1}

# @param: additional packages
args_ruby_package_list=${2}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# - Start installation from https://rvm.io/rvm/security

# Install mpapis public key (might need `gpg2` and or `sudo`)
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

# Download the installer
curl -O https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
curl -O https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc

# Verify the installer signature (might need `gpg2`), and if it validates...
gpg --verify rvm-installer.asc &&

# Run the installer
bash rvm-installer stable

# - End installation from https://rvm.io/rvm/security

# make sure rvm binary is accessible during this session
source /home/vagrant/.rvm/scripts/rvm

# install specified version of ruby
rvm install ${args_ruby_version}

# set the specifed version of ruby as the default version and use it
rvm --default use ${args_ruby_version}
